config/routes.rb
Grubly::Application.routes.draw do

  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks"}

  resources :users do
    resources :photos
  end

  resources :restaurants do
    resources :photos
    resources :items
    resources :orders do
      resources :ordered_items
      member do
        post :send_receipt
      end
    end
  end

  root :to => 'home#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :restaurants
  has_many :orders
  has_many :photos, as: :photoable

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable

  devise :database_authenticatable, :registerable, :omniauthable,
         :recoverable, :rememberable, :trackable, :validatable

  def self.from_omniauth(auth)
    where(auth.slice(:provider, :uid)).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.username = auth.info.nickname
      user.email = "#{user.username}-CHANGEME@twitter.com"
    end
  end

  def self.new_with_session(params, session)
    if session["devise.user_attributes"]
      new(session["devise.user_attributes"], without_protection: true) do |user|
        user.attributes = params
        user.valid?
      end
    else
      super
    end
  end

  def password_required?
    super && provider.blank?
  end

  def update_with_password(params, *options)
    if encrypted_password.blank?
      update_attributes(params, *options)
    else
      super
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
    authorize @users
  end

  def show
    @user = UserDecorator.find(params[:id])
    @orders = @user.orders.where(finalize: true)
    authorize @user
  end

  def new
    redirect_to users_path
  end

  def create
    redirect_to users_path
  end

  def edit
    @user = User.find(params[:id])
    authorize @user
  end

  def update
    @user = User.find(params[:id])
    authorize @user

    if @user.update(user_params)
      redirect_to user_path(@user), notice: "User was successfully updated."
    else
      redirect_to user_path(@user), notice: "Action failed"
    end
  end

  def destroy
    @user = User.find(params[:id])
    authorize @user
    @user.destroy

    redirect_to users_path, notice: "User was successfully destroyed"
  end

private

  def user_params
    params.require(:user).permit(:role, :bio, :email)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="contentsection gray">
  <div class="content">
    <h1>Update Your User Info</h1>
    <div class="form">
      <%= form_for(@user) do |f| %>
        <% if @user.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@user.errors.count, "error") %> prohibited this restaurant from being saved:</h2>

            <ul>
            <% @user.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
            </ul>
          </div>
        <% end %>

        <div class="field">
          <%= f.label :email %><br>
          <%= f.text_field :email %>
        </div>
        <div class="field">
          <%= f.label :bio %><br>
          <%= f.text_field :bio %>
        </div>
        <div class="actions">
          <%= f.submit "Update My Info!" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="contentsection gray">
  <div class="content">
    <h1>User Management</h1>

    <table>
      <th>Username</th>
      <th>Email</th>
      <th>Role</th>

    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= user.email %></td>
        <td><%= user.role %></td>
        <% if user.role != "admin" %>
          <td><%= button_to 'Destroy User', user_path(user), method: :delete, confirm: "Are you sure?" %></td>
        <% end %>
        <% if user.role == nil %>
          <td><%= button_to 'Mark as Restaurant Owner', user_path(user, user: {role: "owner"}), method: :put %></td>
        <% end %>
      </tr>
    <% end %>

    </table>
  </div>
</div>

app/views/users/show.html.erb
<div class="contentsection gray">
  <div class="content">
    <h1><%= @user.username %></h1><br>

    <% @user.photos.each do |photo| %>
      <%= image_tag photo.photo.url(:avatar) %><br>
      <% if policy(@user).edit_photo? %>
        <%= link_to 'Edit Avatar', edit_user_photo_path(@user, photo) %><br>
        <%= link_to 'Delete Avatar', user_photo_path(@user, photo), method: :delete, data: { confirm: 'Are you sure?' } %>
      <% end %>
    <% end %>
    <% policy(@user).edit_photo? && unless @user.photos.any? %>
      <%= link_to 'New Avatar', new_user_photo_path(@user) %>
    <% end %>

    <h3>Member since</h3>
    <p><%= @user.member_since %></p>

    <% if @user.provider? %>
      <h3><%= @user.social_provider %></h3>
      <p><%= link_to "#{@user.social_link}", "http://#{@user.social_provider}.com/#{@user.social_link}" %></p>
    <% end %>

    <h3>Bio</h3>
    <p><%= @user.bio %></p><br><br>
    <% if policy(@user).edit? %>
      <%= link_to 'Update My Email and Bio!', edit_user_path %><br><br>
    <% end %>

    <% if @user.orders.any? %>

    <h6>Here are all your orders for review!</h6><br>

    <table>
      <th>Number</th>
      <th>Restaurant</th>
      <th>Time Order was Placed</th>
      <th>Place Order Again?</th>

      <% @orders.each do |order| %>
        <tr>
          <% @restaurant = order.restaurant.id %>
          <td><%= link_to "Order #{order.id}", restaurant_order_path(@restaurant, order) %></td><br>
          <td><%= link_to "#{order.restaurant.name}", restaurant_path(@restaurant) %></td><br>
          <td><%= l order.created_at %></td>
          <td><%= button_to "Hell yes!" %></td>
        </tr>
      <% end %>

    </table>

    <% else %>
      <h3>Get started with Grubly to see your previous orders here!</h3>
    <% end %>
  </div>
</div>