config/routes.rb
Grubly::Application.routes.draw do

  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks"}

  resources :users do
    resources :photos
  end

  resources :restaurants do
    resources :photos
    resources :items
    resources :orders do
      resources :ordered_items
      member do
        post :send_receipt
      end
    end
  end

  root :to => 'home#index'

end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :user
  belongs_to :restaurant
  has_many :ordered_items
  has_many :items, through: :ordered_items
  accepts_nested_attributes_for :ordered_items, allow_destroy: true

  def inventory_check(order, restaurant)
    @order = order
    @restaurant = restaurant

    @restaurant.items.each do |item|
      check_each_dish(item, @order)
      item.update(:inventory => item.inventory)
    end
  end

  def check_each_dish(item, order)
    @item = item
    @order = order

    end_inventory = @item.inventory
    @order.ordered_items.each do |ordered_item|
      if ordered_item.item_id == @item.id
        end_inventory = (@item.inventory - ordered_item.quantity)
      else
        end_inventory = @item.inventory
      end
      @item.inventory = end_inventory
    end
  end

  def inventory_check_before_deletion(order, restaurant)
    @order = order
    @restaurant = restaurant

    @restaurant.items.each do |item|
      check_each_dish_before_deletion(item, @order)
      item.update(:inventory => item.inventory)
    end
  end

  def check_each_dish_before_deletion(item, order)
    @item = item
    @order = order

    end_inventory = @item.inventory
    @order.ordered_items.each do |ordered_item|
      if ordered_item.item_id == @item.id
        end_inventory = (@item.inventory + ordered_item.quantity)
      else
        end_inventory = @item.inventory
      end
      @item.inventory = end_inventory
    end
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_filter :load_restaurant
  before_action :set_order, only: [:show, :edit, :update, :destroy, :send_receipt]

  # GET /orders
  def index
    @orders = @restaurant.orders.all
  end

  # GET /orders/1
  def show
  end

  # GET /orders/new
  def new
    @order = @restaurant.orders.new
    @ordered_item = @order.ordered_items.build
    @items = @restaurant.items
    @items_by_category = @items.group_by{ |t| t.subcategory }
  end

  # GET /orders/1/edit
  def edit
    authorize @order
  end

  # POST /orders
  def create
    @order = @restaurant.orders.new(order_params)
    authorize @order

    if @order.save
      @order.inventory_check(@order, @restaurant)
      current_user.orders << @order
      respond_to do |format|
        format.html { redirect_to restaurant_order_path(@restaurant, @order), notice: 'Order was successfully created.' }
        format.js
      end
    else
      render action: 'new'
    end
    OrderMailer.order_sent(@restaurant, @order).deliver
  end

  # PATCH/PUT /orders/1
  def update
    authorize @order

    if @order.update(order_params)
      @order.inventory_check(@order, @restaurant)
      respond_to do |format|
        format.html { redirect_to restaurant_orders_url, notice: 'Order was successfully updated.' }
        format.js
      end
    else
      render action: 'edit'
    end
  end

  # DELETE /orders/1
  def destroy
    authorize @order
    @order.inventory_check_before_deletion(@order, @restaurant)
    @order.destroy
    respond_to do |format|
      format.html { redirect_to  restaurant_orders_url, notice: 'Order was successfully destroyed.' }
      format.js
    end
  end

  def send_receipt
    authorize @order
    OrderMailer.send_receipt(@order).deliver
    redirect_to restaurant_orders_url, notice: 'Receipt was successfully sent!'
  end

  private

    def load_restaurant
      @restaurant = Restaurant.find(params[:restaurant_id])
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = @restaurant.orders.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def order_params
      params.require(:order).permit(:item_id, :quantity, :note, :restaurant_id,
        :user_id, :user, :item_to_be_added, :finalize, :completed, :ordered_item, ordered_items_attributes: [:ordered_item_id, :restaurant_id, '_destroy', :item_id, :quantity, :note, :user_id])
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.erb
<%= form_for [@restaurant, @order], remote: true do |f| %>
  <% if @order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% @order.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :note, "List any special notes for this order (e.g. allergies)" %><br>
    <%= f.text_field :note %>
  </div>
  <%= associated_fields(f, :ordered_items, @ordered_items) %>
  <%= link_to_add_fields "Add Another Item", f, :ordered_items %><br><br>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/orders/_order.html.erb
<% if current_user && policy(order).show? %>
        <tr>
          <td><%= link_to "Order #{order.id}", restaurant_order_path(@restaurant, order) %></td>
          <td><%= order.user.username %></td>
          <td><%= order.note %></td>
          <% if current_user && policy(order).show? %>
            <% if order.finalize? %>
              <td>Finalized!</td>
            <% else %>
              <td>Not Finalized!</td>
            <% end %>
          <% end %>
            <td><%= l order.created_at %></td>

          <% if current_user && policy(order).show? %>
            <td><%= link_to 'Show', restaurant_order_path(@restaurant, order) %> </td>
          <% end %>

          <% if current_user && policy(order).edit_after_final? && (order.completed? == false) %>
            <td><%= button_to 'Order Completed!', restaurant_order_path(@restaurant, order, order: {completed: true}), method: :put %></td>
          <% elsif order.completed? %>
            <td>Order Filled!</td>
          <% else %>
            <td>Not Filled!</td>
          <% end %>

          <% if current_user && policy(order).edit_after_final? %>
            <td><%= button_to 'Send Receipt!', send_receipt_restaurant_order_path(@restaurant, order), method: :post %></td>
          <% end %>

          <% if current_user && (order.finalize? == false && policy(order).update?) || policy(order).edit_after_final? %>
            <td><%= link_to 'Edit Order Note', edit_restaurant_order_path(@restaurant, order) %></td>
          <% end %>

          <% if current_user && (order.finalize? == false && policy(order).destroy?) || policy(order).edit_after_final? %>
            <td><%= link_to 'Destroy', restaurant_order_path(@restaurant, order), method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end %>

        </tr>
        <% end %>

app/views/orders/_ordered_item_fields.html.erb
<fieldset>
  <div class="field">
    <%= f.label :dish_name %><br>
    <%= f.collection_select :item_id, @restaurant.items, :id, :dish_name %>
  </div>
  <div class="field">
    <%= f.label :quantity %><br>
    <%= f.number_field :quantity %>
  </div>
  <div class="field">
    <%= f.label :note %><br>
    <%= f.text_field :note %>
  </div>
  <%= f.hidden_field :_destroy %>
  <%= link_to "Remove Item From Order", '#', class: "remove_fields" %>
</fieldset>

app/views/orders/create.js.erb
$('#new_order').fadeOut();
$('#customer_order').fadeIn();
$('#order_data td').first().html('<%= link_to "Order #{@order.id}", restaurant_order_path(@restaurant, @order) %>');
$('#order_data td').first().next().html('<%= @order.user.username %>');
$('#order_data td').first().next().next().html('<%= @order.note %>');
$('#order_data td').first().next().next().next().html('Not Finalized!');
$('#order_data td').first().next().next().next().next().html('<%= @order.created_at.in_time_zone("Pacific Time (US & Canada)").strftime("%m/%d/%Y at %I:%M%p") %>');
$('#building_order').fadeIn();
$('#finalize_prompt').fadeIn();

app/views/orders/edit.html.erb
<div class="contentsection gray">
  <div class="content">
    <h1>Editing order</h1>

    <%= render 'form' %>

    <%= link_to 'Show', restaurant_order_path(@restaurant, @order) %> |
    <%= link_to 'Cancel', restaurant_orders_path(@restaurant) %>
  </div>
</div>

app/views/orders/index.html.erb
<div class="contentsection beige">
  <div class="content">
    <h1>Orders for <%= "#{@restaurant.name}" %></h1>

    <% if (current_user && current_user.orders.any? { |order| order.restaurant_id == @restaurant.id }) || policy(@restaurant).update? %>
      <table>
        <thead>
          <tr>
            <th>Order Number</th>
            <th>For</th>
            <th>Special Notes</th>
            <th>Finalized?</th>
            <th>Time Ordered</th>
            <th>Details</th>
            <th>Order Filled?</th>
            <% if policy(@restaurant).update? %>
            <th>Send Receipt?</th>
            <% end %>
            <th>Edit Note</th>
            <th>Destroy Order</th>
          </tr>
        </thead>

        <tbody>

          <%= render @orders %>

        </tbody>
      </table>
    <% elsif current_user.nil? %>
    <p>Please <%= link_to 'sign in', new_user_session_path %> for full site functionality!</p>
    <% else %>
    <p>It looks like you don't have any orders for this restaurant yet! Would you like to <%= link_to 'build one?', new_restaurant_order_path(@restaurant) %></p>
    <% end %>
    <br>

    <%= link_to 'Back to Restaurant', restaurant_path(@restaurant) %><br>
  </div>
</div>

app/views/orders/new.html.erb
<div class="contentsection beige">
  <div class="content">
    <h1><%= "#{@restaurant.name}"%></h1>
    <h2>Some catchy tag line</h2>
    <div id="menu">
      <div class="menusection">
        <% @items_by_category.each do |subcat, item| %>
          <h2><%= subcat %></h2>
          <div class="cols clearfix">

          <% for dish in item %>
            <% column_count = 0 %>
            <% if column_count % 2 == 0 %>
              <div class="col1">
            <% else %>
              <div class="col2">
            <% end %>

                <div class="menuitem", id="<%= dish.id %>">
                  <h3><%= dish.dish_name %>
                    <% if current_user && policy(dish).update? %>
                      <%= link_to 'Details', restaurant_item_path(@restaurant, dish) %>
                    <% end %>
                  </h3>
                  <p><%= dish.description %></p>
                  <% if dish.cents < 10 %>
                  <p class="price"><%= "$#{dish.dollars}.0#{dish.cents}" %></p>
                  <% else %>
                  <p class="price"><%= "$#{dish.dollars}.#{dish.cents}" %></p>
                  <% end %>
                  <p class="calories"><%= dish.inventory %></p>
                </div>
              </div>

            <% column_count = column_count + 1 %>
          <% end %>

          </div>
        <% end %>
      </div>
    </div>


    <br>
    <% if current_user && policy(@restaurant).item_create? %>
      <%= link_to 'New Item', new_restaurant_item_path(@restaurant) %><br><br>
    <% end %>

    <h3>Ready to place an order?</h3>

    <%= render 'form' %>

    <div id="customer_order">
      <table>
          <thead>
            <tr>
              <th>Order Number</th>
              <th>For</th>
              <th>Special Notes</th>
              <th>Finalized?</th>
              <th>Time Ordered</th>
            </tr>
          </thead>
          <tbody>
            <tr id="order_data">
              <td></td>
              <td></td>
              <td></td>
              <td></td>
              <td></td>
            </tr>
          </tbody>
      </table>
    </div>
    <br>

    <div id="building_order">

    </div>
      <div id="finalize_prompt">
        <h4><strong>Don't forget to finalize your order!</strong></h4>
        <p>Click on your order in the Order Number column to review before finalizing.</p>
      </div>

    <%= link_to 'Cancel', restaurant_path(@restaurant) %>
    </div>
  </div>
</div>

app/views/orders/show.html.erb
<div class="contentsection beige">
  <div class="content">
    <p id="notice"><%= notice %></p>

    <p>
      <strong>Order Number:</strong>
      <%= @order.id %>
    </p>

    <p>
      <strong>Different Items:</strong>
      <%= @order.items.count %>
    </p>

    <p>
      <strong>Special Notes:</strong>
      <%= @order.note %>
    </p>

    <table>
      <thead>
        <tr>
          <th>Dish name</th>
          <th>Price</th>
          <th>Quantity</th>
        </tr>
      </thead>


      <tbody>
        <% @order.ordered_items.each do |item| %>
          <tr>
            <td><%= @restaurant.items.find(item.item_id).dish_name %></td>
            <td><%= "#{@restaurant.items.find(item.item_id).dollars}.#{@restaurant.items.find(item.item_id).cents}" %></td>
            <td><%= item.quantity %></td>
            <% if current_user && @order.finalize? == false || policy(@order).edit_after_final? %>
              <td><%= link_to 'Edit Item', edit_restaurant_order_ordered_item_path(@restaurant, @order, item) %></td>
              <td><%= link_to 'Remove Item', restaurant_order_ordered_item_path(@restaurant, @order, item), method: :delete %></td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>

    <br><br><br>

    <% if current_user && @order.finalize? %>
      <%= "Your order has already been finalized!" %><br><br>
    <% elsif current_user && (@order.ordered_items.count > 0) && policy(@order).finalize? %>
      <%= button_to 'Finalize Order', restaurant_order_path(@restaurant, @order, order: {finalize: true}), method: :put %><br>
    <% end %>

    <% if current_user && @order.finalize? == false  && policy(@order).show? %>
      <%= link_to 'Add to Order', new_restaurant_order_ordered_item_path(@restaurant, @order, @ordered_item) %><br>
    <% end %>
    <% if current_user && policy(@order).update? %>
      <%= link_to 'Edit Order Note', edit_restaurant_order_path(@restaurant, @order) %> |
    <% end %>
    <%= link_to 'Back', restaurant_orders_path %>
    </div>
  </div>
</div>