config/routes.rb
Grubly::Application.routes.draw do

  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks"}

  resources :users do
    resources :photos
  end

  resources :restaurants do
    resources :photos
    resources :items
    resources :orders do
      resources :ordered_items
      member do
        post :send_receipt
      end
    end
  end

  root :to => 'home#index'

end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  has_many :users
  has_many :orders
  has_many :customers, class_name: "User", through: :orders
  has_many :items, dependent: :destroy
  has_many :photos, as: :photoable
  geocoded_by :address
  after_validation :geocode
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]

  # GET /restaurants
  def index
    @restaurants = Restaurant.all
  end

  # GET /restaurants/1
  def show
    @items = @restaurant.items
  end

  # GET /restaurants/new
  def new
    @restaurant = Restaurant.new
  end

  # GET /restaurants/1/edit
  def edit
    authorize @restaurant
  end

  # POST /restaurants
  def create
    @restaurant = Restaurant.new(restaurant_params)
    @restaurant.owner = current_user.id
    authorize @restaurant

    if @restaurant.save
      redirect_to @restaurant, notice: 'Restaurant was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /restaurants/1
  def update
    authorize @restaurant

    if @restaurant.update(restaurant_params)
      redirect_to @restaurant, notice: 'Restaurant was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /restaurants/1
  def destroy
    authorize @restaurant
    @restaurant.destroy
    redirect_to restaurants_url, notice: 'Restaurant was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_restaurant
      @restaurant = Restaurant.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def restaurant_params
      params.require(:restaurant).permit(:name, :address, :category, :phone_number, :website, :owner)
    end
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/restaurants/_form.html.erb
<%= form_for(@restaurant) do |f| %>
  <% if @restaurant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@restaurant.errors.count, "error") %> prohibited this restaurant from being saved:</h2>

      <ul>
      <% @restaurant.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :category %><br>
    <%= f.text_field :category %>
  </div>
  <div class="field">
    <%= f.label :phone_number %><br>
    <%= f.text_field :phone_number %>
  </div>
  <div class="field">
    <%= f.label :website %><br>
    <%= f.text_field :website %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/restaurants/edit.html.erb
<div class="contentsection beige">
  <div class="content">
    <h1>Editing restaurant</h1>

    <%= render 'form' %>

    <%= link_to 'Show', @restaurant %> |
    <%= link_to 'Back', restaurants_path %>
  </div>
</div>

app/views/restaurants/index.html.erb
<div class="contentsection beige">
  <div class="content">
    <h1>Listing All Restaurants</h1>

    <table>
      <thead>
        <tr>
          <th>Name</th>
          <th>Address</th>
          <th>Category</th>
          <th>Phone number</th>
          <th>Website</th>
          <th>Show</th>
          <% if current_user && policy(Restaurant).create? %>
            <th>Edit</th>
          <% end %>
          <% if current_user && policy(Restaurant).create? %>
            <th>Destroy</th>
          <% end %>
        </tr>
      </thead>

      <tbody>
        <% @restaurants.each do |restaurant| %>
          <tr id="<%= dom_id(restaurant) %>">
            <td ><%= restaurant.name %></td>
            <td><%= restaurant.address %></td>
            <td><%= restaurant.category %></td>
            <td><%= restaurant.phone_number %></td>
            <td><%= restaurant.website %></td>
            <td><%= link_to 'Details', restaurant %></td>
            <% if current_user && policy(restaurant).update? %>
              <td><%= link_to 'Edit', edit_restaurant_path(restaurant) %></td>
            <% end %>
            <% if current_user && policy(restaurant).destroy? %>
              <td><%= link_to 'Destroy', restaurant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>

    <br>

    <% if current_user && policy(Restaurant).create? %>
      <%= link_to 'New Restaurant', new_restaurant_path %>
    <% end %>
  </div>
</div>

app/views/restaurants/new.html.erb
<div class="contentsection beige">
  <div class="content">
    <h1>New restaurant</h1>

    <%= render 'form' %>

    <%= link_to 'Back', restaurants_path %>
    </div>
  </div>
</div>

app/views/restaurants/show.html.erb
<div class="contentsection gray">
  <div class="content">
    <h1><%= @restaurant.name %></h1>

    <p>
      <strong>Name:</strong>
      <%= @restaurant.name %>
    </p>

    <p>
      <strong>Address:</strong>
      <%= @restaurant.address %>
    </p>

    <p>
      <strong>Category:</strong>
      <%= @restaurant.category %>
    </p>

    <p>
      <strong>Phone number:</strong>
      <%= @restaurant.phone_number %>
    </p>

    <p>
      <strong>Website:</strong>
      <%= @restaurant.website %>
    </p>

    <img src="http://maps.googleapis.com/maps/api/staticmap?center=<%= @restaurant.latitude %>,<%= @restaurant.longitude %>&zoom=16&size=300x300&markers=color:green|<%= @restaurant.latitude %>, <%= @restaurant.longitude %>&maptype=roadmap&sensor=false">

    <% @restaurant.photos.each do |photo| %>
      <%= image_tag photo.photo.url(:medium) %><br>
      <% if current_user && policy(@restaurant).update? %>
        <%= link_to 'Edit Photo', edit_restaurant_photo_path(@restaurant, photo) %><br>
        <%= link_to 'Destroy Photo', restaurant_photo_path(@restaurant, photo), method: :delete, data: { confirm: 'Are you sure?' } %><br>
      <% end %>
    <% end %><br>


    <% if current_user %>
      <br><br><strong><%= link_to 'View Our Menu', new_restaurant_order_path(@restaurant) %></strong><br>
      <strong><%= link_to 'Order History', restaurant_orders_path(@restaurant) %></strong><br><br>
    <% else %>
      <br><br><p><%= link_to 'Sign in', new_user_session_path %> to view the menu and place an order!</p><br><br>
    <% end %>

    <% if current_user && policy(@restaurant).update? %>
      <%= link_to 'Add a Photo', new_restaurant_photo_path(@restaurant) %><br>
      <%= link_to 'Add Items to Menu', restaurant_items_path(@restaurant) %><br><br>
      <%= link_to 'Edit', edit_restaurant_path(@restaurant) %> |
    <% end %>
    <%= link_to 'Back', restaurants_path %><br>
  </div>
</div>
<div class="contentsection beige">
  <div class="content">
    <div class="left">
      <h1>Specials</h1>
      <p class="callout">Our have a full bar that includes one of the largest selections of brews one can imagine.</p><br>
      <div class="special">
        <h2>Brunch</h2>
        <p><i>11:00am-3:00pm All Week</i></p>
        <p>15 bottomless mimosas and Bloody Marys</p>
      </div>
      <div class="special">
        <h2>Happy Hour</h2>
        <p><i>5:00pm-7:00pm All Week</i></p>
        <p>$5 Select Draft Pints & Champagne Cocktails, $6 Featured Sparkling, Red, & White Wines, $7 Sobieski Vodka Martinis, $8 Mojitos, & Discounted Bites, appetizers.</p>
      </div>
      <div class="special">
        <h2>Dinner</h2>
        <p><i>7:00pm-10:00pm Fridays Only</i></p>
        <p>Half off select wines and brew. Half off all appetizers.</p>
      </div>
    </div>
  </div>
</div>