config/routes.rb
Grubly::Application.routes.draw do

  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks"}

  resources :users do
    resources :photos
  end

  resources :restaurants do
    resources :photos
    resources :items
    resources :orders do
      resources :ordered_items
      member do
        post :send_receipt
      end
    end
  end

  root :to => 'home#index'

end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :restaurant
  has_many :ordered_items
  has_many :orders, through: :ordered_items

  validates :dish_name,   presence: true
  validates :description, presence: true
  validates :dollars,     presence: true,
                          numericality: { greater_than_or_equal_to: 0 }
  validates :cents,       presence: true,
                          numericality: { greater_than_or_equal_to: 0 }
  validates :inventory,   presence: true,
                          numericality: { greater_than_or_equal_to: 0 }
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_filter :load_restaurant
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  def index
    @items = @restaurant.items.all
    @items_by_category = @items.group_by{ |t| t.subcategory }
  end

  # GET /items/1
  def show
  end

  # GET /items/new
  def new
    @item = @restaurant.items.new
  end

  # GET /items/1/edit
  def edit
    authorize @item
  end

  # POST /items
  def create
    @item = @restaurant.items.new(item_params)
    @item.restaurant_id = @restaurant.id
    authorize @item

    respond_to do |format|
      if @item.save
        format.html { redirect_to restaurant_items_url, notice: 'Item was successfully created.' }
        format.js
      else
        render action: 'new'
      end
    end
  end

  # PATCH/PUT /items/1
  def update
    authorize @item

    if @item.update(item_params)
      respond_to do |format|
        format.html { redirect_to restaurant_items_url, notice: 'Item was successfully updated.' }
        format.js
      end
    else
      render action: 'edit'
    end
  end

  # DELETE /items/1
  def destroy
    authorize @item
    @item.destroy
    respond_to do |format|
      format.html { redirect_to restaurant_items_url, notice: 'Item was successfully destroyed.' }
      format.js
    end
  end

  private
    def load_restaurant
      @restaurant = Restaurant.find(params[:restaurant_id])
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = @restaurant.items.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def item_params
      params.require(:item).permit(:item_id, :dish_name, :dollars, :cents, :description, :subcategory,
        :inventory, :restaurant_id)
    end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_edit_form.html.erb
<%= simple_form_for [@restaurant, @item] do |f| %>
  <%= f.error_notification %>
  <%= f.input :dish_name %>
  <%= f.input :description %>
  <%= f.input :dollars %>
  <%= f.input :cents %>
  <%= f.input :subcategory, label: "Menu Group", hint: "Appetizers, Drinks, Etc" %>
  <%= f.input :inventory %>
  <%= f.button :submit %>
<% end %>

app/views/items/_form.html.erb
<%= simple_form_for [@restaurant, @item], remote: true do |f| %>
  <%= f.error_notification %>
  <%= f.input :dish_name %>
  <%= f.input :description %>
  <%= f.input :dollars %>
  <%= f.input :cents %>
  <%= f.input :subcategory, label: "Menu Group", hint: "Appetizers, Drinks, Etc" %>
  <%= f.input :inventory %>
  <%= f.button :submit %>
<% end %>

<%= link_to 'Cancel', restaurant_items_path, id: "cancel_link" %>

app/views/items/_item.html.erb
<div class="menuitem", id="<%= item.id %>">
  <h3><%= item.dish_name %></h3>
  <p><%= item.description %></p>
  <p class="price"><%= "$#{item.dollars}.#{item.cents}" %></p>
  <p class="calories"><%= item.inventory %></p>
  <% if current_user && policy(item).update? %>
    <%= link_to 'Edit', edit_restaurant_item_path(@restaurant, item), id: "edit_link_#{item.id}", remote: true %>
  <% end %>
  <% if current_user && policy(item).destroy? %>
    <%= link_to 'Destroy', restaurant_item_path(@restaurant, item), id: "delete_link_#{item.id}", method: :delete, data: { confirm: 'Are you sure?', remote: true } %>
  <% end %>
</div>

app/views/items/create.js.erb
$('#new_item').remove();
$('#new_link').show();
$("#cancel_link").remove();
$('.menusection').append('<%= j render(@item) %>');

app/views/items/destroy.js.erb
$("div#<%= @item.id %>").remove();

app/views/items/edit.html.erb
<div class="content">
  <h1>Editing item</h1>

  <%= render 'edit_form' %>
  <%= link_to 'Show', [@restaurant, @item] %> |
  <%= link_to 'Back', restaurant_items_path %>
</div>

app/views/items/index.html.erb
<div class="contentsection beige">
  <div class="content">
    <h1>Some Tag Line</h1>
    <h2>With a sub tag line</h2>
    <div id="menu">
      <div class="menusection">
        <% @items_by_category.each do |subcat, item| %>
          <h2><%= subcat %></h2>
          <div class="cols clearfix">

          <% for dish in item %>
            <% column_count = 0 %>
            <% if column_count % 2 == 0 %>
              <div class="col1">
            <% else %>
              <div class="col2">
            <% end %>

                <div class="menuitem", id="<%= dish.id %>">
                  <h3><%= dish.dish_name %></h3>
                  <p><%= dish.description %></p>
                  <% if dish.cents < 10 %>
                  <p class="price"><%= "$#{dish.dollars}.0#{dish.cents}" %></p>
                  <% else %>
                  <p class="price"><%= "$#{dish.dollars}.#{dish.cents}" %></p>
                  <% end %>
                  <p class="calories"><%= dish.inventory %></p>
                  <% if current_user && policy(dish).update? %>
                    <%= link_to 'Edit', edit_restaurant_item_path(@restaurant, dish), id: "edit_link_#{dish.id}" %>
                  <% end %>
                  <% if current_user && policy(dish).destroy? %>
                    <%= link_to 'Destroy', restaurant_item_path(@restaurant, dish), id: "delete_link_#{dish.id}", method: :delete, data: { confirm: 'Are you sure?', remote: true } %>
                  <% end %>
                </div>
              </div>

            <% column_count = column_count + 1 %>
          <% end %>

          </div>
        <% end %>
      </div>
    </div>

    <% if current_user && policy(@restaurant).update? %>
      <%= link_to 'New Item', new_restaurant_item_path, id: "new_link", remote: true %><br>
    <% end %>

    <%= link_to 'Back', restaurant_path(@restaurant) %>

  </div>
</div>

app/views/items/new.html.erb
<div class="content">

<h1>New item</h1>

<%= render 'form' %>

</div>

app/views/items/new.js.erb
$('#new_link').hide().after('<%= j render("form") %>');
$("#cancel_link").on("click", function() {
    $('#new_item').remove();
    $("#cancel_link").remove();
    $('#new_link').show();
});

app/views/items/show.html.erb
<<div class="content">
<p id="notice"><%= notice %></p>

<p>
  <strong>Dish name:</strong>
  <%= @item.dish_name %>
</p>

<p>
  <strong>Price:</strong>
  <%= "#{@item.dollars}.#{@item.cents}" %>
</p>

<p>
  <strong>Description:</strong>
  <%= @item.description %>
</p>

<p>
  <strong>Subcategory:</strong>
  <%= @item.subcategory %>
</p>

<p>
  <strong>Inventory:</strong>
  <%= @item.inventory %>
</p>

<% if current_user && policy(@item).update? %>
  <%= link_to 'Edit', edit_restaurant_item_path(@restaurant, @item) %> |
<% end %>
<%= link_to 'Back', new_restaurant_order_path(@restaurant) %>
</div>

app/views/items/update.js.erb
$('#edit_item_<%= @item.id %>').remove();
$('#new_link').show();
$("#cancel_link").remove();
$('#menu-list').append('<%= j render(@item) %>');